Fixed 3

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -8,10 +8,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: First step
-        run: # установим тайм-аут
-          sleep 10
-          #exit 1
+      - name: Sleep or Error
+        id: error-step # задаём id чтобы поймать ошибку в failure
+        run: # установим тайм-аут или сгенерим ошибку
+          #sleep 10
+          exit 1
       - name: Runs on Canceled # здесь canceled вернёт True, если предидущие шаги были отменены, в иных случаях этот run пропустится
         if: ${{ cancelled() }}
         run: echo "Runs on canceled"
@@ -25,7 +26,8 @@ jobs:
         run: echo "Runs on Success"
 
       - name: Runs on Failure # этот шаг запустится, если где то ранее произойдет ошибка
-        if: ${{ failure() }}
+        #if: ${{ failure() }}
+        if: ${{ failure() && steps.error-step.conclusion == 'failure' }} # проверяем нужный шаг по id
         run: echo "Runs on Failure"
 
   second_job:
