Fixed

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -10,7 +10,8 @@ jobs:
     steps:
       - name: First step
         run: # установим тайм-аут
-          sleep 30
+          #sleep 30
+          exit 1
       - name: Runs on Canceled # здесь canceled вернёт True, если предидущие шаги были отменены, в иных случаях этот run пропустится
         if: ${{ cancelled() }}
         run: echo "Runs on canceled"
@@ -26,3 +27,10 @@ jobs:
       - name: Runs on Failure # этот шаг запустится, если где то ранее произойдет ошибка
         if: ${{ failure() }}
         run: echo "Runs on Failure"
+
+  second_job:
+    needs: job # ставим зависимость от первого job
+    if: ${{ failure() }} # если он провалится
+    steps:
+      - run: echo "Job was failed"
+
